import { NameSpace } from '../../const';
import { Comment } from '../../types/comment';
import { Offer } from '../../types/offer';
import { Property } from '../../types/property';
import { State } from '../../types/state';
import { UserData } from '../../types/user-data';

export const getOffers = (state: State): Offer[] => state[NameSpace.Data].data;
export const getOffersSortedByCity = (state: State): Offer[] => state[NameSpace.Data].offersSortedByCity;
export const getOffersSortedByType = (state: State): Offer[] => state[NameSpace.Data].offersSortedByType;
export const getIsDataLoaded = (state: State): boolean => state[NameSpace.Data].isDataLoaded;
export const getActiveCity = (state: State): string => state[NameSpace.Data].activeCity;
export const getNearbyOffers = (state: State): Offer[] => state[NameSpace.Data].nearbyOffers;
export const getProperty = (state: State): Property | null => state[NameSpace.Data].property;
export const getSelectedType = (state: State): string => state[NameSpace.Data].selectedType;
export const getComments = (state: State): Comment[] => state[NameSpace.Data].comments;
export const getReviewFormStatus = (state: State): string => state[NameSpace.Data].reviewFormStatus;
export const getFavoriteOffers = (state: State): Offer[] => state[NameSpace.Data].favoriteOffers;
export const getIsFavoriteLoaded = (state: State): boolean => state[NameSpace.Data].isFavoriteLoaded;
export const getUserData = (state: State): UserData | null => state[NameSpace.Data].user;
